name: Release

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v7

    - name: Publish documentation
      run: sbt docs/docusaurusPublishGhpages